config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "confirmation", to: "pages#confirmation"

  devise_for :users

  resources :services do
    resources :appointments, only: [:new, :create]
  end

  resources :appointments, except: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :service

#  validates :user_id, uniqueness: {scope: :service_id}

end

app/models/service.rb
class Service < ApplicationRecord
  geocoded_by :place
  after_validation :geocode, if: :will_save_change_to_place?
  belongs_to :user
  has_many :appointments
  has_one_attached :photo

  validates :price, presence: true
  validates :start_time, presence: true
  validates :duration, presence: true
  validates :plan, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appoinments
  has_many :services
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  

  #validates :first_name, presence: true
  #validates :last_name, presence: true
  #validates :phone_number, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = policy_scope(Appointment)
  end
  
  def new
    @service = Service.find(params[:service_id])
    @appointment = Appointment.new
    authorize @appointment
  end
      
  def create
    service = Service.find(params[:service_id])
    @appointment = Appointment.new(appointment_params.merge({ user_id: current_user.id }))
    @appointment.user = current_user
    authorize @appointment
    @appointment.service = service
    
    if @appointment.save
      redirect_to confirmation_path(service)
    else
      render :new
    end
  end


  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.delete
    authorize @appointment
    redirect_to confirmation_path
    flash[:notice] = "Destruiste tu reserva"
  end
      
  private
      
  def appointment_params
    params.permit(:service_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @services = Service.all.first(3)
    @users = User.all
  end

  def confirmation
    @assigned_to_user = Appointment.select {|app| app.user == current_user }
    @markers = []
    @assigned_to_user.each do |app|
    @markers << { lat: app.service.geocode[0],
      lng: app.service.geocode[1]}
    end
  end  
    
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

def index
  if params[:query].present? && params[:date].present? 
    @services = []
     policy_scope(Service).where(place: params[:query]).each do |service|
      if service.start_time.strftime("%Y-%m-%d").include?(params[:date].first) 
        @services << service
      end
   end
  elsif params[:query].present?
    @services = policy_scope(Service).where(place: params[:query])
  elsif params[:date].present? 
    @services = []
    policy_scope(Service).each do |service|
      if service.start_time.strftime("%Y-%m-%d").include?(params[:date].first) 
        @services << service
      end
   end
  else
    @services = policy_scope(Service)
  end
  @users = User.all
  
end

def show
  @service = Service.find(params[:id])
  authorize @service
  
  @markers = 
    [ lat: @service.geocode[0],
      lng: @service.geocode[1]] 
end

def new 
  @service = Service.new
  authorize @service
end


def search
  @services = policy_scope(Service)
  if params[:query].present?
    @services = Service.where(place: params[:query])
  else
    @services = policy_scope(Service)
  end
end

def create
    @service = Service.new(service_params)
    @service.user = current_user
    authorize @service
    if @service.save
        redirect_to service_path(@service)
    else
      render :new
    end       
end



private

  def service_params
    params.require(:service).permit(:duration, :start_time, :price, :plan, :place, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://datacated.com/wp-content/uploads/2019/01/happy.jpg);">
<div class="container">
  <h1  style="color: white">Por favor revisa el servicio antes de <strong>confirmar!</strong></h1>
</div>
</div>
<br>
<div class="container" >
  <h6>Si confirmas el escuchador seleccionado recibira tu correo y se pondrá en contacto contigo pronto!.</h6>
  <h6>Si necesitas cancelar tu cita recuerda hacerlo con <strong> al menos 24 horas de antelación</strong>.</h6>
  <h6>Esto es para que otro usuario tenga posibilidad de tomarla.</h6>
  <br>
  <h6>A confirmar:</h6>
  <br>
    <h6>Nombre del escuchador: <strong><%= @service.user.first_name %>, <%= @service.user.last_name %></h6></strong>
    <h6>Descripción: <strong> <%= @service.plan.capitalize %></h6> </strong>
    <h6>Precio en Pesos ARG: <strong> $ <%= @service.price.to_i %></h6></strong>
    <h6>Fecha: <strong><%= @service.start_time.strftime('%a %d %b %Y') %></h6></strong>
    <h6>Disponibilidad: <strong><%= @service.duration.to_i %> hora(s)</h6></strong>
    <h6>Lugar: <strong><%= @service.place %></h6></strong>
  <br>
  <%= simple_form_for [@service, @appointment] do |f| %>

  <%= f.submit 'Volver', class: "btn btn-gradient" %>
  <% Appointment.create(user: current_user, service: @service) %>
  <%= link_to "Confirmar servicio", confirmation_path(@service), class: "btn btn-gradient" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escuchadores</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="favicon" href="favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <div class="min-vh-100">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/confirmation.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://assets1.drugstorenews.com/styles/hero/s3/2021-06/handshake-hero.jpg?itok=moVjH2S4);">
  <div class="container">
    <h1  style="color: white">Mi perfil</h1>
  </div> 
</div>
<br>
<div class="d-flex justify-content-between flex-column align-items-center" >
  <h5>Mis citas actuales:</h5>
  <div class="col-md-6">
    <div id="map" class="rounded border border-secondary"
      style="width: 600px; height: 300px; margin-bottom: 20px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <br>
  <div class="d-flex justify-content-between align-items-center flex-column">
    <% assigned_to_user = Appointment.select {|app| app.user == current_user } %>
    <% assigned_to_user.each do |app| %>
      <div class="card mb-3 shadow p-3 bg-white rounded">
          <div class="row g-0">
            <div class="col-md-4">
              <%= cl_image_tag app.service.photo.key, class: "img-fluid rounded-start" %>  
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h6>Id del servicio: <%= app.service_id %></h6><h6>Id del usuario: <%= app.user_id %></h6>
                <h6>Nombre del escuchador: <strong><%= app.user.first_name %>, <%= app.user.last_name %></h6></strong>
                <h6>Descripción: <strong> <%= app.service.plan.capitalize %></h6> </strong>
                <h6>Precio Pesos ARG, por hora: <strong>$ <%= app.service.price.to_i %></h6></strong>
                <h6>Fecha: <strong><%= app.service.start_time.strftime('%a %d %b %Y') %></h6></strong>
                <h6>Disponibilidad: <strong><%= app.service.duration.to_i %> hora(s)</h6></strong>
                <h6>Lugar: <strong><%= app.service.place %></h6></strong>
                <%= link_to "Borrar reserva", appointment_path(app.id), method: :delete, data: {confirm: "Está seguro que desea eliminar la reserva?"}, class:"btn btn-sm btn-danger mt-3" %>    

              </div>
            </div>
          </div>    
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490462988459-a92f695ad4a1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80);">
  <div class="container">
    <h1>¿Estás buscando alguien que te acompañe?</h1>
    <p>Escucharte en silencio, caminar juntos, ir a la iglesia y mucho más. </p>
    <div></div>
      <%= form_tag services_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control w-25",
        placeholder: "Ciudad"
        %>
        <%= date_field :date,
        params[:date],
        class: "form-control w-25",
        placeholder: "Fecha"
      %>
    
  <br>
    <%= submit_tag "Buscar", class: "btn btn-gradient" %>


    
    
    
    <%#= link_to "Descubrir más", services_path, class: "btn btn-gradient" %>
  </div>
</div>
<div class="container">
    <h2 class = "text-center mt-5">Populares</h2>
    


    <div class="cards mt-5">
    <% @services.each do |service| %>   
    <%= link_to service_path(service) do %>

    <div class="card-trip">
        <%= cl_image_tag service.photo.key %>
            <div class="card-trip-infos">
            <div>
            <h2><%=  service.plan %></h2>
            <%# <%= link_to "Ver más..", service_path(service) %>
            </div>
            <h2 class="card-trip-pricing">$<%=  service.price.to_i %></h2>            
            <% user = @users.sample %>
              <%# <img src="https://avatars.githubusercontent.com/u/62758510?v=4" alt="user" class= "card-trip-user avatar-bordered"> %>
              <%= cl_image_tag user.photo.key, class: "card-trip-user avatar-bordered" %>
              <%# <%= cl_image_tag user.photo.key, class: "card-trip-user avatar-bordered" %>                                 
        </div>
        </div>
         <% end %>
        <% end %>
    </div>
</div>    



<!--div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Buca a tu escuchador:</h2>

    <%= simple_form_for root_path ,url: services_path , method: "get" do |f| %>
      <%= f.input :query, placeholder: "Ciudad", label: false, required: false %>
      <%= f.input :start_time, placeholder: "Fecha", as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Buscar", class: "btn btn-primary" %>
    <% end %>
  </div-->

  <%#= form_tag services_path, method: :get do %>
  <!--
      <%= text_field_tag :query,
      params[:query],
      class: "form-control w-25",
      placeholder: "Ciudad"
      %>
      <br>
      <%= submit_tag "Buscar", class: "btn btn-gradient" %>
    <% end %>
-->

app/views/services/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.showcaseocala.com/wp-content/uploads/2020/06/Review_Feature.jpg);">
    <h1 class = "text-center mt-5" style="color: white">Todos los servicios </h1>
    </div>

<div class="container">
    

    <div class="cards mt-5">
    <% @services.each do |service| %>
    <%= link_to service_path(service) do %>
    <div class="card-trip">
    
        <%= cl_image_tag service.photo.key %>
            <div class="card-trip-infos">
            <div>
            <h2><%=  service.plan %></h2>
            <%# <%= link_to "Ver más..", service_path(service) %>
            </div>
            <h2 class="card-trip-pricing">$<%=  service.price.to_i %></h2>            
            <% user = @users.sample %>
              <%= cl_image_tag user.photo.key, class: "card-trip-user avatar-bordered" %>                                  
        
        </div>
        
        </div>
        <% end %>
         <% end %>
        
    </div>
    
</div>




<!--

    <div class="cards mt-5">
    <% @services.each do |service| %>
    <div class="card-trip">
        <img src="https://images.unsplash.com/photo-1555696958-c5049b866f6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80" />
           <div class="card-trip-infos">
            <div>
            <h2><%=  service.plan %></h2>
            <%= link_to "Ver mas..", service_path(service) %>
            </div>
            <h2 class="card-trip-pricing">$<%=  service.price %></h2>
            <img src="https://avatars.githubusercontent.com/u/82399802?v=4" class="card-trip-user avatar-bordered" />
        </div>
        </div>
        <% end %>
    </div>
</div>    

-->

app/views/services/new.html.erb
    <h1>Crear nuevo servicio</h1>
    
    <%= simple_form_for @service do |f| %>
	  <%= f.input :start_time %>
      <%= f.input :duration %>
	  <%= f.input :place %>
	  <%= f.input :plan %>
	  <%= f.input :price %>
	  <%= f.submit "Crear nuevo servicio!!" %>
	<% end %>

app/views/services/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.shaulph.ca/wp-content/uploads/2020/10/to-do-list.png);">
  <div class="container">
    <h1>Estás viendo los servicios de:</h1>
    <p><%= @service.user.first_name %>, <%= @service.user.last_name %> </p>
    

    <h4>Seguir buscando</h4>
      <%= form_tag services_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control w-25",
        placeholder: "Ciudad"
        %>
        <%= date_field :date,
        params[:date],
        class: "form-control w-25",
        placeholder: "Fecha"
      %>

  <br>
    <%= submit_tag "Buscar", class: "btn btn-gradient" %>
    <% end %>
    
  <br>
  </div>
</div>


<br>
<div class = "container">

<h3>Detalles del servicio ofrecido:</h1>
<div class="card mb-3 shadow p-3 bg-white rounded" style="max-width: 1200px;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= cl_image_tag @service.photo.key, class: "img-fluid rounded-start" %>  
      
    </div>
    <div class="col-md-8">
      <div class="card-body">

        <h6>Nombre del escuchador: <strong><%= @service.user.first_name %>, <%= @service.user.last_name %></h6></strong>
        <h6>Descripción: <strong> <%= @service.plan.capitalize %></h6> </strong>
        <h6>Precio Pesos ARG, por hora: <strong>$ <%= @service.price.to_i %></h6></strong>
        <h6>Fecha: <strong><%= @service.start_time.strftime('%a %d %b %Y') %></h6></strong>
        <h6>Disponibilidad: <strong><%= @service.duration.to_i %> hora(s)</h6></strong>
        <h6>Lugar: <strong><%= @service.place %></h6></strong>   
        <%= link_to "Agendar servicio", new_service_appointment_path(@service), class: "btn btn-gradient" %>
      </div>
    </div>
  </div>

  <div id="map" class="rounded border border-secondary"
     style="width: 100%; height: 300px"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>



<!--div class="container" >
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Buca a tu escuchador:</h2>

    <%= simple_form_for services_path , method: :get do |f| %>
      <%= f.input :query, placeholder: "Ciudad", label: false, required: false %>
      <%= f.input :start_time, placeholder: "Fecha", as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Buscar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div-->



<!--div class = "container">

  <div class = "card-product-infos">

  <h3>Detalles del servicio ofrecido:</h1>
  <br>
  <h6>Nombre del escuchador: <strong><%= @service.user.first_name %>, <%= @service.user.last_name %></h6></strong>
  <h6>Descripción: <strong> <%= @service.plan.capitalize %></h6> </strong>
  <h6>Precio Pesos ARG, por hora: <strong>$ <%= @service.price.to_i %></h6></strong>
  <h6>Fecha: <strong><%= @service.start_time.strftime('%a %d %b %Y') %></h6></strong>
  <h6>Horas disponible: <strong><%= @service.duration.to_i %></h6></strong>
  <h6>Lugar: <strong><%= @service.place %></h6></strong>

   
   <%= cl_image_tag @service.photo.key, class: "img-thumbnail" %>
  </div>
  


</div>
<br>

<div class = "container">
  <%#= link_to "Generar appointment", new_service_appointment_path(@service) %>
  <%= link_to "Agendar servicio", new_service_appointment_path(@service), class: "btn btn-gradient" %>

</div-->
<%#= link_to "Volver al inicio!", root_path, class: "btn btn-gradient"%>
<%#= link_to "Descubrir más", services_path, class: "btn btn-gradient" %>

</div>


<%= render 'shared/review' %>
</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer border-top mt-5">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Te escuchamos con <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logosvg.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mi perfil", "confirmation", class: "nav-link" %>
        </li>  
        <li class="nav-item dropdown">

          <%# <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%= image_tag "https://secure.gravatar.com/avatar/595f98cd8e237c8a71cc418c65f1d62d?s=1024&d=mm&r=g", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_review.html.erb
<div class = "container mt-5">
    <div class="notification">
    <img src='https://avatars.githubusercontent.com/u/46158176?v=4' class="avatar-large" />
    <div class="notification-content">
        <p class="mb-2"><small>Pedro, Esquel</small><i class="fas fa-star ml-3"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></p>
        <p>No lo dudes. <strong>Recomendado 100%</strong>. Me encantó.</p>
    </div>
    </div>

    <div class="notification">
    <img src='https://avatars.githubusercontent.com/u/79029266?v=4' class="avatar-large"/>
    <div class="notification-content">
        <p class="mb-2"><small>Joaquín, CABA</small><i class="fas fa-star ml-3"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></p>
        <p>Esta experiencia fue <strong>Increíble</strong>. Se lo recomiendo a todo el mundo.</p>
    </div>
    </div>

    <div class="notification">
    <img src='https://avatars.githubusercontent.com/u/83969488?v=4' class="avatar-large" />
    <div class="notification-content">
        <p class="mb-2"><small>Jorge, Don Torcuato</small><i class="fas fa-star ml-3"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></p>
        <p><strong>Buenísimo!</strong> Se lo reservé a mi mamá y quedó feliz.</p>
    </div>
    </div>

    <div class="notification">
    <img src='https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1578521170/x8umjo5g7gbh8astwzly.jpg' class="avatar-large" />
    <div class="notification-content">
        <p class="mb-2"><small>Juana, San Miguel</small><i class="fas fa-star ml-3"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></p>
        <p>Reservo todas las semanas y <strong>me encanta!</strong></p>
    </div>


    </div>

  <p class="card-text"><small class="text-muted">Gracias por confiar en escuchadores.com </small></p> 
</div